"""Rebuild the synthetic data notebook: keep cells 0-7, replace 8+ with new workflow."""
import json

NB_PATH = r"r:\Dropbox\_Code\Projects\irp\helper_scripts\Synthetic_Data_Llama3_3_70B.ipynb"

with open(NB_PATH, "r", encoding="utf-8") as f:
    nb = json.load(f)

# Keep cells 0-7 (intro, GPU check, installation, model loading)
nb["cells"] = nb["cells"][:8]


def md_cell(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source.split("\n")}


def code_cell(source):
    return {"cell_type": "code", "metadata": {}, "source": source.split("\n"), "outputs": [], "execution_count": None}


# ---- New cells ----

nb["cells"].append(md_cell(
    "## Mount Google Drive & Setup Paths\n"
    "Upload the required files to `My Drive/irp_retraining/` before running."
))

nb["cells"].append(code_cell(
    'from google.colab import drive\n'
    'drive.mount("/content/drive")\n'
    '\n'
    'import json\n'
    'from pathlib import Path\n'
    '\n'
    'DRIVE_ROOT = Path("/content/drive/MyDrive/irp_retraining")\n'
    'ASSET_AWARE_DS = DRIVE_ROOT / "datasets" / "ir_playbooks_alpaca_with_assets.jsonl"\n'
    'MITRE_MAPPING = DRIVE_ROOT / "helper_scripts" / "mitre_incident_mapping.json"\n'
    'ASSET_PROFILES = DRIVE_ROOT / "helper_scripts" / "asset_profiles.py"\n'
    '\n'
    'OUTPUT_REWRITTEN = DRIVE_ROOT / "datasets" / "ir_playbooks_alpaca_rewritten.jsonl"\n'
    'OUTPUT_SYNTHETIC = DRIVE_ROOT / "datasets" / "ir_playbooks_synthetic_v2.jsonl"\n'
    '\n'
    '# Verify files exist\n'
    'for p in [ASSET_AWARE_DS, MITRE_MAPPING, ASSET_PROFILES]:\n'
    '    status = "OK" if p.exists() else "MISSING"\n'
    '    print(f"  [{status}] {p}")\n'
))

nb["cells"].append(code_cell(
    '# Load the asset-aware dataset\n'
    'with open(ASSET_AWARE_DS, "r", encoding="utf-8") as f:\n'
    '    all_rows = [json.loads(line) for line in f if line.strip()]\n'
    '\n'
    'asset_aware_rows = [(i, r) for i, r in enumerate(all_rows) if r.get("_asset_aware")]\n'
    'original_rows = [(i, r) for i, r in enumerate(all_rows) if not r.get("_asset_aware")]\n'
    '\n'
    'print(f"Total rows: {len(all_rows)}")\n'
    'print(f"  Asset-aware (need output rewriting): {len(asset_aware_rows)}")\n'
    'print(f"  Original format (keep as-is): {len(original_rows)}")\n'
    '\n'
    '# Load MITRE mapping\n'
    'with open(MITRE_MAPPING, "r", encoding="utf-8") as f:\n'
    '    mitre_data = json.load(f)\n'
    'print(f"\\nMITRE campaigns loaded: {len(mitre_data[\'campaigns\'])}")\n'
))

nb["cells"].append(md_cell(
    "## Job 1: Output Rewriting (Asset-Aware)\n"
    "\n"
    "For each of the 110 asset-aware rows, use the 70B model to rewrite the `output` field\n"
    "so it references specific hostnames, IPs, and tool names from the injected asset context.\n"
    "This teaches the model to produce asset-specific playbooks."
))

nb["cells"].append(code_cell(
    'import torch\n'
    '\n'
    'REWRITE_SYSTEM = (\n'
    '    "You are an incident response expert. You rewrite IR playbooks to reference "\n'
    '    "specific organization assets. You preserve the exact format and all 5 NIST phases."\n'
    ')\n'
    '\n'
    'REWRITE_USER_TEMPLATE = """Below is an IR playbook and the organization\'s asset inventory.\n'
    'Rewrite the playbook so that:\n'
    '1. Generic tool names (EDR, SIEM, Firewall, etc.) are replaced with specific asset names, IPs, and hostnames from the inventory\n'
    '2. Action descriptions reference specific assets by hostname and IP where relevant\n'
    '3. Add an "Affected Assets:" section BEFORE "Final status:" listing each referenced asset and its role in the response\n'
    '4. Keep ALL 5 NIST phases (Identification, Containment, Eradication, Recovery, Lessons Learned)\n'
    '5. Keep the EXACT format: Phase/Action/Tools/Target response time per phase, Final status, Total response duration\n'
    '6. Do NOT add any text before "Playbook:" or after "Total response duration"\n'
    '\n'
    '{asset_context}\n'
    '\n'
    'Original playbook:\n'
    '{original_output}\n'
    '\n'
    'Rewrite the playbook now. Output ONLY the rewritten playbook starting with "Playbook:" and nothing else.\n'
    '"""\n'
    '\n'
    '\n'
    'def rewrite_output(original_output, asset_context, max_new_tokens=1024, temperature=0.3):\n'
    '    """Use the 70B model to rewrite a playbook output to reference specific assets."""\n'
    '    user_content = REWRITE_USER_TEMPLATE.format(\n'
    '        asset_context=asset_context,\n'
    '        original_output=original_output\n'
    '    )\n'
    '    messages = [\n'
    '        {"role": "system", "content": REWRITE_SYSTEM},\n'
    '        {"role": "user", "content": user_content},\n'
    '    ]\n'
    '    inputs = tokenizer.apply_chat_template(\n'
    '        messages, tokenize=True, add_generation_prompt=True, return_tensors="pt"\n'
    '    )\n'
    '    device = "cuda" if torch.cuda.is_available() else "cpu"\n'
    '    inputs = inputs.to(device)\n'
    '    \n'
    '    with torch.no_grad():\n'
    '        outputs = model.generate(\n'
    '            input_ids=inputs,\n'
    '            max_new_tokens=max_new_tokens,\n'
    '            do_sample=True,\n'
    '            temperature=temperature,\n'
    '            top_p=0.95,\n'
    '        )\n'
    '    generated = tokenizer.decode(outputs[0][inputs.shape[-1]:], skip_special_tokens=True).strip()\n'
    '    \n'
    '    # Ensure it starts with "Playbook:"\n'
    '    if "Playbook:" in generated:\n'
    '        generated = generated[generated.index("Playbook:"):]\n'
    '    \n'
    '    return generated\n'
    '\n'
    '\n'
    'def extract_asset_context(input_text):\n'
    '    """Extract the Organization assets: block from the input field."""\n'
    '    marker = "Organization assets:"\n'
    '    idx = input_text.find(marker)\n'
    '    if idx == -1:\n'
    '        return None\n'
    '    return input_text[idx:]\n'
    '\n'
    '\n'
    'def validate_rewrite(text):\n'
    '    """Basic validation that rewrite has the right structure."""\n'
    '    required = ["Phase: Identification", "Phase: Containment", "Phase: Eradication",\n'
    '                "Phase: Recovery", "Phase: Lessons Learned", "Affected Assets:",\n'
    '                "Final status:"]\n'
    '    return all(phrase in text for phrase in required)\n'
    '\n'
    'print("Rewrite functions ready.")\n'
))

nb["cells"].append(code_cell(
    '# Run output rewriting on all asset-aware rows\n'
    'rewritten_rows = list(all_rows)  # copy\n'
    'success = 0\n'
    'failed_indices = []\n'
    '\n'
    'for batch_num, (idx, row) in enumerate(asset_aware_rows):\n'
    '    asset_context = extract_asset_context(row["input"])\n'
    '    if asset_context is None:\n'
    '        print(f"  [SKIP] Row {idx}: no asset context found")\n'
    '        failed_indices.append(idx)\n'
    '        continue\n'
    '\n'
    '    original_output = row["output"]\n'
    '    \n'
    '    # Try up to 2 attempts\n'
    '    rewritten = None\n'
    '    for attempt in range(2):\n'
    '        candidate = rewrite_output(original_output, asset_context)\n'
    '        if validate_rewrite(candidate):\n'
    '            rewritten = candidate\n'
    '            break\n'
    '    \n'
    '    if rewritten:\n'
    '        rewritten_rows[idx] = dict(row)\n'
    '        rewritten_rows[idx]["output"] = rewritten\n'
    '        success += 1\n'
    '    else:\n'
    '        failed_indices.append(idx)\n'
    '    \n'
    '    if (batch_num + 1) % 10 == 0:\n'
    '        print(f"  Rewritten {batch_num + 1}/{len(asset_aware_rows)} (success: {success})")\n'
    '    \n'
    '    # Save checkpoint every 25 rows\n'
    '    if (batch_num + 1) % 25 == 0:\n'
    '        with open(OUTPUT_REWRITTEN, "w", encoding="utf-8") as f:\n'
    '            for r in rewritten_rows:\n'
    '                clean = {k: v for k, v in r.items() if not k.startswith("_")}\n'
    '                f.write(json.dumps(clean) + "\\n")\n'
    '        print(f"  [Checkpoint saved to {OUTPUT_REWRITTEN}]")\n'
    '\n'
    'print(f"\\nOutput rewriting complete: {success}/{len(asset_aware_rows)} successful")\n'
    'if failed_indices:\n'
    '    print(f"Failed rows (kept original output): {failed_indices}")\n'
    '\n'
    '# Final save\n'
    'with open(OUTPUT_REWRITTEN, "w", encoding="utf-8") as f:\n'
    '    for r in rewritten_rows:\n'
    '        clean = {k: v for k, v in r.items() if not k.startswith("_")}\n'
    '        f.write(json.dumps(clean) + "\\n")\n'
    'print(f"Saved to {OUTPUT_REWRITTEN}")\n'
))

nb["cells"].append(md_cell(
    "## Job 2: Synthetic Playbook Generation (MITRE-Seeded)\n"
    "\n"
    "Generate 50-80 new Alpaca-format playbooks using MITRE ATT&CK campaigns as seeds.\n"
    "Each campaign is used to generate 3-4 variations."
))

nb["cells"].append(code_cell(
    'SYNTH_SYSTEM = (\n'
    '    "You are an incident response expert. Generate detailed incident response playbooks "\n'
    '    "in the exact format specified. Include all 5 NIST phases. Use real security tool names. "\n'
    '    "Be specific and actionable."\n'
    ')\n'
    '\n'
    'SYNTH_USER_TEMPLATE = """Generate an incident response playbook for this real-world attack scenario.\n'
    '\n'
    'Attack context:\n'
    '- Campaign: {campaign_name}\n'
    '- Incident type: {incident_type}\n'
    '- MITRE ATT&CK tactics: {tactics}\n'
    '- Target asset: {target_asset}\n'
    '- Severity: {severity}\n'
    '- Background: {notes}\n'
    '\n'
    'Generate the output in this EXACT format (no JSON, just plain text):\n'
    '\n'
    'Playbook:\n'
    '\n'
    'Phase: Identification\n'
    'Action: [specific actions for this incident]\n'
    'Tools: [real tool names like CrowdStrike Falcon, Splunk, Palo Alto, etc.]\n'
    'Target response time (minutes): [number]\n'
    '\n'
    'Phase: Containment\n'
    'Action: [specific containment actions]\n'
    'Tools: [real tool names]\n'
    'Target response time (minutes): [number]\n'
    '\n'
    'Phase: Eradication\n'
    'Action: [specific eradication actions]\n'
    'Tools: [real tool names]\n'
    'Target response time (minutes): [number]\n'
    '\n'
    'Phase: Recovery\n'
    'Action: [specific recovery actions]\n'
    'Tools: [real tool names]\n'
    'Target response time (minutes): [number]\n'
    '\n'
    'Phase: Lessons Learned\n'
    'Action: [specific post-incident actions]\n'
    'Tools: [real tool names]\n'
    'Target response time (minutes): [number]\n'
    '\n'
    'Final status: Resolved\n'
    'Total response duration (minutes): [sum of all phases]\n'
    '\n'
    'Output ONLY the playbook text above. No explanations, no JSON, no markdown.\n'
    '"""\n'
    '\n'
    '\n'
    'def generate_playbook(campaign, max_new_tokens=768, temperature=0.7):\n'
    '    """Generate a single synthetic playbook from a MITRE campaign seed."""\n'
    '    # Handle both string and object-style tactics\n'
    '    def fmt_tactic(t):\n'
    '        if isinstance(t, dict):\n'
    '            tid = f" ({t[\'technique_id\']})" if t.get("technique_id") else ""\n'
    '            return f"{t[\'tactic\']}: {t[\'technique\']}{tid}"\n'
    '        return str(t)\n'
    '    tactics_str = "; ".join(fmt_tactic(t) for t in campaign["tactics"])\n'
    '    user_content = SYNTH_USER_TEMPLATE.format(\n'
    '        campaign_name=campaign["name"],\n'
    '        incident_type=campaign["incident_type"],\n'
    '        tactics=tactics_str,\n'
    '        target_asset=campaign["target_asset"],\n'
    '        severity=campaign["severity"],\n'
    '        notes=campaign.get("notes", f"Attributed to {(campaign.get(\'attributed_group\') or {}).get(\'name\', \'Unknown\')} ({campaign.get(\'attack_id\', \'\')}). Source: {campaign.get(\'source_url\', \'\')}"),\n'
    '    )\n'
    '    messages = [\n'
    '        {"role": "system", "content": SYNTH_SYSTEM},\n'
    '        {"role": "user", "content": user_content},\n'
    '    ]\n'
    '    inputs = tokenizer.apply_chat_template(\n'
    '        messages, tokenize=True, add_generation_prompt=True, return_tensors="pt"\n'
    '    )\n'
    '    device = "cuda" if torch.cuda.is_available() else "cpu"\n'
    '    inputs = inputs.to(device)\n'
    '    \n'
    '    with torch.no_grad():\n'
    '        outputs = model.generate(\n'
    '            input_ids=inputs,\n'
    '            max_new_tokens=max_new_tokens,\n'
    '            do_sample=True,\n'
    '            temperature=temperature,\n'
    '            top_p=0.95,\n'
    '        )\n'
    '    generated = tokenizer.decode(outputs[0][inputs.shape[-1]:], skip_special_tokens=True).strip()\n'
    '    \n'
    '    if "Playbook:" in generated:\n'
    '        generated = generated[generated.index("Playbook:"):]\n'
    '    \n'
    '    return generated\n'
    '\n'
    '\n'
    'def validate_synthetic(output_text):\n'
    '    """Validate that a synthetic playbook has all required phases."""\n'
    '    required_phases = ["Phase: Identification", "Phase: Containment", "Phase: Eradication",\n'
    '                       "Phase: Recovery", "Phase: Lessons Learned"]\n'
    '    has_phases = all(p in output_text for p in required_phases)\n'
    '    has_final = "Final status:" in output_text\n'
    '    # Check for real tool names (at least 2)\n'
    '    real_tools = ["CrowdStrike", "Splunk", "Palo Alto", "Veeam", "Suricata", "Darktrace",\n'
    '                  "Carbon Black", "Velociraptor", "YARA", "Wireshark", "Nessus", "OpenVAS",\n'
    '                  "Snort", "Cloudflare", "Okta", "Duo", "CyberArk", "MISP", "Volatility",\n'
    '                  "Burp Suite", "Tenable", "Qualys", "SentinelOne", "Microsoft Defender",\n'
    '                  "Wazuh", "ELK", "Elastic", "Nagios", "Zabbix"]\n'
    '    tool_count = sum(1 for t in real_tools if t.lower() in output_text.lower())\n'
    '    return has_phases and has_final and tool_count >= 2\n'
    '\n'
    '\n'
    'def build_alpaca_row(campaign, output_text):\n'
    '    """Convert a synthetic playbook into Alpaca format."""\n'
    '    # Format tactics: handle both string and object-style\n'
    '    def fmt_line(t):\n'
    '        if isinstance(t, dict):\n'
    '            tid = f" ({t[\'technique_id\']})" if t.get("technique_id") else ""\n'
    '            return f"- {t[\'tactic\']}: {t[\'technique\']}{tid}"\n'
    '        return f"- {t}"\n'
    '    tactics_lines = "\\n".join(fmt_line(t) for t in campaign["tactics"])\n'
    '    \n'
    '    # Extract initial vector from first tactic\n'
    '    first = campaign["tactics"][0]\n'
    '    if isinstance(first, dict):\n'
    '        initial_vector = first["technique"]\n'
    '    else:\n'
    '        initial_vector = first.split(":")[1].strip().split("(")[0].strip() if ":" in first else first\n'
    '    \n'
    '    tags = campaign["incident_type"].lower().replace(" ", "_")\n'
    '    \n'
    '    input_text = (\n'
    '        f"Incident type: {campaign[\'incident_type\']}\\n"\n'
    '        f"Target asset: {campaign[\'target_asset\']}\\n"\n'
    '        f"Detection source: MITRE ATT&CK Campaign - {campaign[\'name\']}\\n"\n'
    '        f"Initial vector: {initial_vector}\\n"\n'
    '        f"Tactics and techniques:\\n{tactics_lines}\\n"\n'
    '        f"Severity: {campaign[\'severity\']}\\n"\n'
    '        f"Tags: {tags}, mitre_attack"\n'
    '    )\n'
    '    \n'
    '    return {\n'
    '        "instruction": "Create a detailed incident response playbook for the following cyber incident.",\n'
    '        "input": input_text,\n'
    '        "output": output_text,\n'
    '    }\n'
    '\n'
    'print("Synthetic generation functions ready.")\n'
))

nb["cells"].append(code_cell(
    'import random\n'
    'random.seed(42)\n'
    '\n'
    'campaigns = mitre_data["campaigns"]\n'
    'VARIATIONS_PER_CAMPAIGN = 3  # 21 campaigns x 3 = 63 target rows\n'
    'TARGET_COUNT = len(campaigns) * VARIATIONS_PER_CAMPAIGN\n'
    'MAX_ATTEMPTS = TARGET_COUNT * 3\n'
    '\n'
    'synthetic_rows = []\n'
    'campaign_idx = 0\n'
    'variation = 0\n'
    'attempts = 0\n'
    '\n'
    'print(f"Generating ~{TARGET_COUNT} synthetic playbooks from {len(campaigns)} MITRE campaigns...")\n'
    'print(f"({VARIATIONS_PER_CAMPAIGN} variations each)\\n")\n'
    '\n'
    'while len(synthetic_rows) < TARGET_COUNT and attempts < MAX_ATTEMPTS:\n'
    '    campaign = campaigns[campaign_idx]\n'
    '    \n'
    '    # Vary temperature slightly for diversity\n'
    '    temp = 0.6 + (variation * 0.15)  # 0.6, 0.75, 0.9\n'
    '    output_text = generate_playbook(campaign, temperature=min(temp, 0.95))\n'
    '    attempts += 1\n'
    '    \n'
    '    if validate_synthetic(output_text):\n'
    '        row = build_alpaca_row(campaign, output_text)\n'
    '        synthetic_rows.append(row)\n'
    '        variation += 1\n'
    '        \n'
    '        if variation >= VARIATIONS_PER_CAMPAIGN:\n'
    '            variation = 0\n'
    '            campaign_idx += 1\n'
    '            if campaign_idx >= len(campaigns):\n'
    '                break\n'
    '        \n'
    '        if len(synthetic_rows) % 10 == 0:\n'
    '            print(f"  Generated {len(synthetic_rows)}/{TARGET_COUNT}")\n'
    '    else:\n'
    '        print(f"  [REJECT] Campaign: {campaign[\'name\']} (attempt {attempts})")\n'
    '\n'
    'print(f"\\nSynthetic generation complete: {len(synthetic_rows)} rows")\n'
    'print(f"  Attempts: {attempts}, Rejection rate: {(attempts - len(synthetic_rows))/max(attempts,1):.1%}")\n'
    '\n'
    '# Save synthetic rows\n'
    'with open(OUTPUT_SYNTHETIC, "w", encoding="utf-8") as f:\n'
    '    for r in synthetic_rows:\n'
    '        f.write(json.dumps(r) + "\\n")\n'
    'print(f"Saved to {OUTPUT_SYNTHETIC}")\n'
))

nb["cells"].append(md_cell(
    "## Summary & Validation"
))

nb["cells"].append(code_cell(
    'from collections import Counter\n'
    '\n'
    '# Summarize rewritten dataset\n'
    'with open(OUTPUT_REWRITTEN, "r", encoding="utf-8") as f:\n'
    '    rewritten = [json.loads(l) for l in f if l.strip()]\n'
    '\n'
    'print(f"=== Rewritten Base Dataset ===")\n'
    'print(f"Total rows: {len(rewritten)}")\n'
    'has_affected = sum(1 for r in rewritten if "Affected Assets:" in r.get("output", ""))\n'
    'print(f"Rows with Affected Assets section: {has_affected}")\n'
    '\n'
    '# Summarize synthetic dataset\n'
    'with open(OUTPUT_SYNTHETIC, "r", encoding="utf-8") as f:\n'
    '    synthetic = [json.loads(l) for l in f if l.strip()]\n'
    '\n'
    'print(f"\\n=== Synthetic Dataset ===")\n'
    'print(f"Total rows: {len(synthetic)}")\n'
    '\n'
    'synth_types = Counter()\n'
    'for r in synthetic:\n'
    '    for line in r.get("input", "").split("\\n"):\n'
    '        if line.startswith("Incident type:"):\n'
    '            synth_types[line.replace("Incident type:", "").strip()] += 1\n'
    '            break\n'
    '\n'
    'print("Synthetic incident type distribution:")\n'
    'for itype, count in synth_types.most_common():\n'
    '    print(f"  {itype}: {count}")\n'
    '\n'
    'print(f"\\n=== Files saved to Google Drive ===")\n'
    'print(f"  {OUTPUT_REWRITTEN}")\n'
    'print(f"  {OUTPUT_SYNTHETIC}")\n'
    'print(f"\\nDownload these files and place in your local project datasets/ folder.")\n'
))

# Write the modified notebook
with open(NB_PATH, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Notebook rebuilt: {len(nb['cells'])} cells")
print("Cells 0-7: Setup + model loading (unchanged)")
print("Cells 8+: New workflow (Drive mount, rewriting, synthetic gen)")
