"""Mock connector that returns realistic demo asset data."""

from connectors.base import AssetConnector


class MockConnector(AssetConnector):
    """Returns hardcoded demo assets for presentation and testing."""

    def fetch_assets(self) -> list[dict]:
        return [
            # Endpoint Protection
            {
                "name": "ws-corp-pool",
                "type": "workstation",
                "vendor_product": "Dell OptiPlex 7090",
                "network_zone": "corporate",
                "ip_or_subnet": "10.10.1.0/24",
                "role": "",
                "managed_by": "CrowdStrike Falcon",
                "criticality": "medium",
                "notes": "150 Windows 11 workstations",
            },
            {
                "name": "laptop-exec-pool",
                "type": "laptop",
                "vendor_product": "Lenovo ThinkPad X1",
                "network_zone": "corporate",
                "ip_or_subnet": "DHCP",
                "role": "",
                "managed_by": "CrowdStrike Falcon",
                "criticality": "high",
                "notes": "25 executive laptops - BitLocker enabled",
            },
            {
                "name": "srv-dc-01",
                "type": "server",
                "vendor_product": "Dell PowerEdge R750",
                "network_zone": "datacenter",
                "ip_or_subnet": "10.20.1.10",
                "role": "primary domain controller",
                "managed_by": "CrowdStrike Falcon",
                "criticality": "critical",
                "notes": "Primary AD DS",
            },
            {
                "name": "srv-dc-02",
                "type": "server",
                "vendor_product": "Dell PowerEdge R750",
                "network_zone": "datacenter",
                "ip_or_subnet": "10.20.1.11",
                "role": "secondary domain controller",
                "managed_by": "CrowdStrike Falcon",
                "criticality": "critical",
                "notes": "Secondary AD DS",
            },
            # Network Security
            {
                "name": "fw-perimeter-01",
                "type": "firewall",
                "vendor_product": "Palo Alto PA-850",
                "network_zone": "dmz",
                "ip_or_subnet": "10.0.0.1",
                "role": "perimeter filtering",
                "managed_by": "",
                "criticality": "critical",
                "notes": "Managed via Panorama",
            },
            {
                "name": "fw-internal-01",
                "type": "firewall",
                "vendor_product": "Palo Alto PA-450",
                "network_zone": "datacenter",
                "ip_or_subnet": "10.20.0.1",
                "role": "east-west segmentation",
                "managed_by": "",
                "criticality": "high",
                "notes": "Segments corporate from datacenter",
            },
            {
                "name": "ids-core-01",
                "type": "ids",
                "vendor_product": "Suricata 7.0",
                "network_zone": "datacenter",
                "ip_or_subnet": "10.20.0.5",
                "role": "intrusion detection",
                "managed_by": "",
                "criticality": "high",
                "notes": "Feeds alerts to Splunk",
            },
            {
                "name": "proxy-web-01",
                "type": "proxy",
                "vendor_product": "Zscaler ZIA",
                "network_zone": "corporate",
                "ip_or_subnet": "cloud",
                "role": "web filtering and SSL inspection",
                "managed_by": "",
                "criticality": "medium",
                "notes": "All outbound HTTP/HTTPS routed through Zscaler",
            },
            # Identity & Access
            {
                "name": "mfa-provider",
                "type": "mfa",
                "vendor_product": "Duo Security",
                "network_zone": "cloud",
                "ip_or_subnet": "cloud",
                "role": "multi-factor authentication",
                "managed_by": "",
                "criticality": "critical",
                "notes": "Enforced for VPN - email - and admin consoles",
            },
            {
                "name": "pam-vault-01",
                "type": "pam",
                "vendor_product": "CyberArk PAS",
                "network_zone": "datacenter",
                "ip_or_subnet": "10.20.1.50",
                "role": "privileged access management",
                "managed_by": "",
                "criticality": "critical",
                "notes": "All admin credentials vaulted here",
            },
            # Monitoring & Logging
            {
                "name": "siem-splunk-01",
                "type": "siem",
                "vendor_product": "Splunk Enterprise 9.2",
                "network_zone": "datacenter",
                "ip_or_subnet": "10.20.2.10",
                "role": "centralized log aggregation and alerting",
                "managed_by": "",
                "criticality": "critical",
                "notes": "90-day hot retention - 1-year warm",
            },
            {
                "name": "edr-console",
                "type": "edr",
                "vendor_product": "CrowdStrike Falcon",
                "network_zone": "cloud",
                "ip_or_subnet": "cloud",
                "role": "endpoint detection and response",
                "managed_by": "",
                "criticality": "critical",
                "notes": "Covers all endpoints and servers",
            },
            {
                "name": "ndr-sensor-01",
                "type": "ndr",
                "vendor_product": "Darktrace",
                "network_zone": "datacenter",
                "ip_or_subnet": "10.20.0.8",
                "role": "network traffic analysis",
                "managed_by": "",
                "criticality": "high",
                "notes": "Monitors east-west and north-south traffic",
            },
            # Servers & Critical Services
            {
                "name": "srv-db-01",
                "type": "database",
                "vendor_product": "Microsoft SQL Server 2022",
                "network_zone": "datacenter",
                "ip_or_subnet": "10.20.3.10",
                "role": "primary business database",
                "managed_by": "",
                "criticality": "critical",
                "notes": "Contains customer PII - encrypted at rest",
            },
            {
                "name": "srv-web-01",
                "type": "web_server",
                "vendor_product": "Nginx on Ubuntu 22.04",
                "network_zone": "dmz",
                "ip_or_subnet": "10.0.0.20",
                "role": "public-facing web application",
                "managed_by": "",
                "criticality": "high",
                "notes": "Behind Palo Alto WAF policy",
            },
            {
                "name": "srv-file-01",
                "type": "file_server",
                "vendor_product": "Windows Server 2022",
                "network_zone": "datacenter",
                "ip_or_subnet": "10.20.3.20",
                "role": "shared file storage",
                "managed_by": "",
                "criticality": "medium",
                "notes": "2 TB - DFS replication",
            },
            {
                "name": "srv-mail-01",
                "type": "email_server",
                "vendor_product": "Microsoft Exchange Online",
                "network_zone": "cloud",
                "ip_or_subnet": "cloud",
                "role": "email and calendaring",
                "managed_by": "",
                "criticality": "high",
                "notes": "Hybrid config - MX via cloud",
            },
            {
                "name": "srv-dns-01",
                "type": "dns",
                "vendor_product": "Windows DNS",
                "network_zone": "datacenter",
                "ip_or_subnet": "10.20.1.10",
                "role": "internal DNS resolution",
                "managed_by": "",
                "criticality": "critical",
                "notes": "Co-hosted on srv-dc-01",
            },
            # Backup & Recovery
            {
                "name": "backup-veeam-01",
                "type": "backup",
                "vendor_product": "Veeam Backup and Replication 12",
                "network_zone": "datacenter",
                "ip_or_subnet": "10.20.4.10",
                "role": "primary backup server",
                "managed_by": "",
                "criticality": "critical",
                "notes": "Daily full backups - 4-hour RPO",
            },
            {
                "name": "backup-offsite",
                "type": "dr_site",
                "vendor_product": "AWS S3 Glacier",
                "network_zone": "cloud",
                "ip_or_subnet": "cloud",
                "role": "offsite backup copy",
                "managed_by": "",
                "criticality": "critical",
                "notes": "30-day retention - immutable",
            },
            {
                "name": "nas-archive-01",
                "type": "nas",
                "vendor_product": "Synology RS1221+",
                "network_zone": "datacenter",
                "ip_or_subnet": "10.20.4.20",
                "role": "archive and cold storage",
                "managed_by": "",
                "criticality": "medium",
                "notes": "RAID 6 - 20 TB",
            },
            # Network Topology
            {
                "name": "switch-core-01",
                "type": "switch",
                "vendor_product": "Cisco Catalyst 9300",
                "network_zone": "datacenter",
                "ip_or_subnet": "10.20.0.2",
                "role": "core switching",
                "managed_by": "",
                "criticality": "high",
                "notes": "Trunk ports to all datacenter VLANs",
            },
            {
                "name": "router-wan-01",
                "type": "router",
                "vendor_product": "Cisco ISR 4451",
                "network_zone": "dmz",
                "ip_or_subnet": "10.0.0.2",
                "role": "WAN gateway",
                "managed_by": "",
                "criticality": "high",
                "notes": "Dual ISP failover",
            },
            {
                "name": "ap-corp-pool",
                "type": "access_point",
                "vendor_product": "Cisco Meraki MR46",
                "network_zone": "corporate",
                "ip_or_subnet": "DHCP",
                "role": "wireless access",
                "managed_by": "",
                "criticality": "medium",
                "notes": "40 APs across 3 floors",
            },
        ]
